sonar.organization=<your_sonar_org_key>
sonar.projectKey=<your_project_key>
sonar.projectName=Intro-to-SWE-Project
sonar.sourceEncoding=UTF-8


sonar.sources=src,public
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.test.jsx
